-- SPDX-License-Identifier: AGPL-3.0-only
-- Phase 1.1: multi-resolution derivatives (thumbnails + previews).
--
-- Adds R2-key columns for the two derivative variants generated by the
-- thumbnails worker (`lib/processing/generateThumbnails.ts`):
--   * thumbnail_key — 256px long-edge WebP (grid view)
--   * preview_key   — 1080px long-edge WebP (lightbox view)
--   * thumbnail_generated_at — timestamp of last successful generation
--
-- All columns are nullable: legacy assets and non-image assets stay NULL.
-- Additive + idempotent — safe to re-run.

ALTER TABLE fonto.assets
  ADD COLUMN IF NOT EXISTS thumbnail_key          text,
  ADD COLUMN IF NOT EXISTS preview_key            text,
  ADD COLUMN IF NOT EXISTS thumbnail_generated_at timestamp with time zone;
